-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Country"
(
    country_id character(10) COLLATE pg_catalog."default" NOT NULL,
    country_name character varying(50) COLLATE pg_catalog."default",
    region character(10) COLLATE pg_catalog."default",
    CONSTRAINT dim_country_pkey PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public."Medal"
(
    medal_id character(10) COLLATE pg_catalog."default" NOT NULL,
    country_medal character(50) COLLATE pg_catalog."default",
    city character(30) COLLATE pg_catalog."default",
    discipline_title character(40) COLLATE pg_catalog."default",
    participant_type character(20) COLLATE pg_catalog."default",
    event_gender character(20) COLLATE pg_catalog."default",
    medal_type character(20) COLLATE pg_catalog."default",
    CONSTRAINT "Medal_pkey" PRIMARY KEY (medal_id)
);

CREATE TABLE IF NOT EXISTS public."Time"
(
    year_id character(10) COLLATE pg_catalog."default" NOT NULL,
    game_year integer,
    game_session character(20) COLLATE pg_catalog."default",
    CONSTRAINT dim_time_b_pkey PRIMARY KEY (year_id)
);

CREATE TABLE IF NOT EXISTS public.fact_table
(
    health_id character(10) COLLATE pg_catalog."default" NOT NULL,
    population_id character(10) COLLATE pg_catalog."default",
    country_id character(10) COLLATE pg_catalog."default",
    time_id character(10) COLLATE pg_catalog."default",
    depressive_disorders numeric,
    schizophrenia numeric,
    bipolar_disorder numeric,
    eating_disorder numeric,
    anxiety_disorder numeric,
    medal_id character(1) COLLATE pg_catalog."default",
    CONSTRAINT fact_table_pkey PRIMARY KEY (health_id)
);

CREATE TABLE IF NOT EXISTS public.population
(
    population_id character(10) COLLATE pg_catalog."default" NOT NULL,
    country_population character(10) COLLATE pg_catalog."default",
    "1980" character(10) COLLATE pg_catalog."default",
    "1981" character(10) COLLATE pg_catalog."default",
    "1982" character(10) COLLATE pg_catalog."default",
    "1983" character(10) COLLATE pg_catalog."default",
    "1984" character(10) COLLATE pg_catalog."default",
    "1985" character(10) COLLATE pg_catalog."default",
    "1986" character(10) COLLATE pg_catalog."default",
    "1987" character(10) COLLATE pg_catalog."default",
    "1988" character(10) COLLATE pg_catalog."default",
    "1989" character(10) COLLATE pg_catalog."default",
    "1990" character(10) COLLATE pg_catalog."default",
    "1991" character(10) COLLATE pg_catalog."default",
    "1992" character(10) COLLATE pg_catalog."default",
    "1993" character(10) COLLATE pg_catalog."default",
    "1994" character(10) COLLATE pg_catalog."default",
    "1995" character(10) COLLATE pg_catalog."default",
    "1996" character(10) COLLATE pg_catalog."default",
    "1997" character(10) COLLATE pg_catalog."default",
    "1998" character(10) COLLATE pg_catalog."default",
    "1999" character(10) COLLATE pg_catalog."default",
    "2000" character(10) COLLATE pg_catalog."default",
    "2001" character(10) COLLATE pg_catalog."default",
    "2002" character(10) COLLATE pg_catalog."default",
    "2003" character(10) COLLATE pg_catalog."default",
    "2004" character(10) COLLATE pg_catalog."default",
    "2005" character(10) COLLATE pg_catalog."default",
    "2006" character(10) COLLATE pg_catalog."default",
    "2007" character(10) COLLATE pg_catalog."default",
    "2008" character(10) COLLATE pg_catalog."default",
    "2009" character(10) COLLATE pg_catalog."default",
    "2010" character(10) COLLATE pg_catalog."default",
    "2011" character(10) COLLATE pg_catalog."default",
    "2012" character(10) COLLATE pg_catalog."default",
    "2013" character(10) COLLATE pg_catalog."default",
    "2014" character(10) COLLATE pg_catalog."default",
    "2015" character(10) COLLATE pg_catalog."default",
    "2016" character(10) COLLATE pg_catalog."default",
    "2017" character(10) COLLATE pg_catalog."default",
    "2018" character(10) COLLATE pg_catalog."default",
    "2019" character(10) COLLATE pg_catalog."default",
    "2020" character(10) COLLATE pg_catalog."default",
    "2021" character(10) COLLATE pg_catalog."default",
    "2022" character(10) COLLATE pg_catalog."default",
    "2023" character(10) COLLATE pg_catalog."default",
    CONSTRAINT population_pkey PRIMARY KEY (population_id)
);

ALTER TABLE IF EXISTS public.fact_table
    ADD CONSTRAINT fact_table_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES public."Country" (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fact_table
    ADD CONSTRAINT fact_table_medal_id_fkey FOREIGN KEY (medal_id)
    REFERENCES public."Medal" (medal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fact_table
    ADD CONSTRAINT fact_table_population_id_fkey FOREIGN KEY (population_id)
    REFERENCES public.population (population_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fact_table
    ADD CONSTRAINT fact_table_time_id_fkey FOREIGN KEY (time_id)
    REFERENCES public."Time" (year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;